services:

  redis:
    image: redis:7
    container_name: payflow-redis
    ports:
      - "6379:6379"

  eureka-server:
    image: payflow-eureka
    container_name: payflow-eureka
    ports:
      - "8761:8761"

  config-server:
    image: payflow-config
    container_name: payflow-config
    ports:
      - "8888:8888"

  mysql:
    image: mysql:8.0
    container_name: payflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: payflow_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  auth-service:
    image: payflow-auth
    container_name: payflow-auth

    ports:
      - 8081:8081
    depends_on:
      - config-server
      - eureka-server
      - mysql


    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://payflow-config:8888

  user-service:
    image: payflow-user
    container_name: payflow-user

    ports:
      - "8082:8082"

    depends_on:
      - config-server
      - eureka-server
      - mysql

    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://payflow-config:8888

  wallet-service:
    image: payflow-wallet
    container_name: payflow-wallet

    ports:
      - "8083:8083"

    depends_on:
      - config-server
      - eureka-server
      - mysql

    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://payflow-config:8888

  gateway-service:
    image: payflow-gateway
    container_name: payflow-gateway

    ports:
      - "8080:8080"

    depends_on:
      - eureka-server
      - config-server

    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://payflow-config:8888

volumes:
  mysql-data: